version: 1

site_url: https://koubk.tech
display_url: https://koubk.tech

backend:
  name: git-gateway
  repo: orkunseyman/gatsby-starter-netlify-cms
  branch: main

update_configs:
  - package_manager: javascript
    directory: /
    update_schedule: live
    allowed_updates:
      - match:
          update_type: security
    automerged_updates:
      - match:
          dependency_type: all
          update_type: in_range
    version_requirement_updates: widen_ranges